# Generated by Django 5.0.7 on 2024-08-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_no',
            new_name='regno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
